global:
  edition: ce
  hosts:
    domain: gitlab.local
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  initialRootPassword:
    secret: gitlab-root-password
    key: password


prometheus:
  install: false

registry:
  enabled: false

gitlab-runner:
  install: false

nginx-ingress:
  controller:
    replicaCount: 1

gitlab:
  kas:
    enabled: false

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

  webservice:
    minReplicas: 1
    maxReplicas: 1
    workerProcesses: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1.5Gi

  sidekiq:
    pods:
      - name: all-in-1
        concurrency: 2
        resources:
          requests:
            memory: 512Mi
            cpu: 50m
          limits:
            memory: 2Gi