Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ofrikelS" do |node|
    node.vm.hostname = "ofrikelS"
    node.vm.network "private_network", ip: "192.168.56.110"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "ofrikelS"
      vb.cpus = 1
      vb.memory = 1024
    end

    node.vm.provision "shell", path: "scripts/server.sh"
  end
end
