Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # -------- Server --------
  config.vm.define "ofrikelS" do |server|
    server.vm.hostname = "ofrikelS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "ofrikelS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # -------- Worker --------
  config.vm.define "ofrikelSW" do |worker|
    worker.vm.hostname = "ofrikelSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "ofrikelSW"
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
