Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # VM name
  config.vm.hostname = "iot-p3"

  # Resources (important for k3d + ArgoCD)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 2
  end

  # Sync your repo (optional but convenient)
  config.vm.synced_folder ".", "/home/vagrant/iot"

  # Provision: just update base packages
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y git curl
  SHELL
end