Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "ofrikelP3" do |vm|
    vm.vm.hostname = "ofrikelP3"
    vm.vm.network "private_network", ip: "192.168.56.120"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "ofrikelP3"
    end

    vm.vm.provision "shell", path: "scripts/install.sh"
  end
end
